;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        dabbrev-expand
        eval-last-sexp
        forward-sexp
        ido-find-file
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-delete-char
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        python-backspace
        python-indent-dedent-line-backspace
        sgml-slash
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        yas-expand
        yas-expand-from-trigger-key
        ))
