(set-face-background 'helm-selection "#002730")
(set-face-foreground 'helm-ff-file (face-foreground 'default))
(set-face-foreground 'helm-ff-executable (face-foreground 'default))
(set-face-foreground 'helm-ff-directory "antique white")
(set-face-foreground 'helm-ff-invalid-symlink (face-foreground 'default))
(set-face-foreground 'helm-ff-symlink (face-foreground 'default))
(set-face-foreground 'helm-source-header "antique white")
(set-face-bold-p 'helm-source-header t)
(set-face-font 'helm-source-header (face-font 'default))
(setq helm-exit-idle-delay 0)

(setq helm-exit-idle-delay 0)
(setq helm-buffer-max-length nil)

(global-set-key (kbd "C-x b") 'helm-buffers-list)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-c C-h l") 'helm-locate)
(global-set-key (kbd "C-c C-h o") 'helm-occur)
(global-set-key (kbd "C-c C-h m") 'helm-all-mark-rings)
(global-set-key (kbd "C-c C-h w") 'helm-man-woman)

(provide 'setup-helm)
